version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      product-catalog-service:
        condition: service_started
      currency-service:
        condition: service_started
      payment-service:
        condition: service_started
      email-service:
        condition: service_started
      checkout-service:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5001-5011:5001-5011"

  prometheus:
    image: "prom/prometheus:latest"
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"

  product-catalog-service:
    image: smj8612/google_online_boutique:latest
    container_name: product-catalog-service
    expose:
      - "5001"
    deploy:
      replicas: 1
    command:
      - /bin/sh
      - -c
      - uvicorn product_catalog_service:app --log-level critical --host 0.0.0.0 --port 5001

  currency-service:
    image: smj8612/google_online_boutique:latest
    container_name: currency-service
    expose:
      - "5002"
    deploy:
      replicas: 1
    command:
      - /bin/sh
      - -c
      - uvicorn currency_service:app --log-level critical --host 0.0.0.0 --port 5002

  payment-service:
    image: smj8612/google_online_boutique:latest
    container_name: payment-service
    expose:
      - "5003"
    deploy:
      replicas: 1
    command:
      - /bin/sh
      - -c
      - uvicorn payment_service:app --log-level critical  --host 0.0.0.0 --port 5003

  shipping-service:
    image: smj8612/google_online_boutique:latest
    container_name: shipping-service
    expose:
      - "5004"
    deploy:
      replicas: 1
    command:
      - /bin/sh
      - -c
      - uvicorn shipping_service:app --log-level critical  --host 0.0.0.0 --port 5004

  email-service:
    image: smj8612/google_online_boutique:latest
    container_name: email-service
    expose:
      - "5005" # needed for microservice
    deploy:
      replicas: 1
    command:
      - /bin/sh
      - -c
      - uvicorn email_service:app --log-level critical  --host 0.0.0.0 --port 5005

  checkout-service:
    image: smj8612/google_online_boutique:latest
    container_name: checkout-service
    expose:
      - "5008"
    deploy:
      replicas: 1
    command:
      - /bin/sh
      - -c
      - uvicorn checkout_service:app --log-level critical  --host 0.0.0.0 --port 5008

  runq-exporter:
    image: smj8612/runq-exporter:latest
    privileged: true
    container_name: runq-exporter
    ports:
      - "8000:8000"
    depends_on:
      product-catalog-service:
        condition: service_started
      currency-service:
        condition: service_started
      payment-service:
        condition: service_started
      shipping-service:
        condition: service_started
      email-service:
        condition: service_started
      checkout-service:
        condition: service_started
      prometheus:
        condition: service_started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /home/ec2-user/runq_result:/home/ec2-user/runq_result
