version: "3.9"
services:
  nginx: # Internal network for the services
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - unique-id-service
    ports:
      #      - "9435-9446:9435-9446"
      - "5001-5011:5001-5011"

  prometheus: # Monitoring Tools for collecting metrics and logs
    image: "prom/prometheus:latest"
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"



  unique-id-service:
    image: smj8612/media_reservation_mj:latest
    privileged: true # needed for ebpf_exporter
    hostname: "unique-id-service"
    ports:
      - "9435-9450:9435" # for ebpf_exporter
    volumes:
      - "/sys:/sys:ro"
      - "/usr/src:/usr/src:ro"
      - "/lib/modules:/lib/modules:ro"
    # For Nginx
    expose:
      - "5001" # needed for microservice
    deploy:
      replicas: 1
    # End of Nginx
    environment:
      - OTEL_SERVICE_NAME=UniqueIdService # The name of the service for OpenTelemetry
    command:
      - /bin/sh
      - -c
      - |
        uvicorn unique_id_service:app --log-level critical --host 0.0.0.0 --port 5001 &
        cd ../../
        while ! ~/go/bin/ebpf_exporter --config.file=go/ebpf_exporter/examples/runqlat.yaml --web.listen-address=":9435"
        do
          sleep 0.01
        done


  text-service:
    image: smj8612/media_reservation_mj:latest
    privileged: true # needed for ebpf_exporter
    volumes:
      - '/sys:/sys:ro'
      - '/usr/src:/usr/src:ro'
      - '/lib/modules:/lib/modules:ro'
    expose:
      - "5002" # will distribute by nginx
    ports:
      - "9451-9466:9451" # for ebpf_exporter
    deploy:
      replicas: 1
    environment:
      - OTEL_SERVICE_NAME=TextService # The name of the service for OpenTelemetry
    command:
      - /bin/sh
      - -c
      - |
        uvicorn upload_text_service:app --log-level critical --host 0.0.0.0 --port 5002 &
        cd ../../
        while ! ~/go/bin/ebpf_exporter --config.file=go/ebpf_exporter/examples/runqlat.yaml --web.listen-address=":9451"
        do
          sleep 0.01
        done

  user-service:
    image: smj8612/media_reservation_mj:latest
    privileged: true # needed for ebpf_exporter
    volumes:
      - '/sys:/sys:ro'
      - '/usr/src:/usr/src:ro'
      - '/lib/modules:/lib/modules:ro'
    expose:
      - "5003" # needed for microservice
    ports:
      - "9467-9482:9467"
    deploy:
      replicas: 1
    environment:
      - OTEL_SERVICE_NAME=UserService # The name of the service for OpenTelemetry
    command:
      - /bin/sh
      - -c
      - |
        uvicorn user_service:app --log-level critical  --host 0.0.0.0 --port 5003 &
        cd ../../
        while ! ~/go/bin/ebpf_exporter --config.file=go/ebpf_exporter/examples/runqlat.yaml --web.listen-address=":9467"
        do
          sleep 0.01
        done

  user-storage-mongodb:
    image: mongo
    container_name: user-storage-mongodb
    ports:
      - '27017:27017'
    command: mongod --quiet --logpath /dev/null


  rating-service:
    image: smj8612/media_reservation_mj:latest
    privileged: true # needed for ebpf_exporter
    volumes:
      - '/sys:/sys:ro'
      - '/usr/src:/usr/src:ro'
      - '/lib/modules:/lib/modules:ro'
    expose:
      - "5004" # needed for microservice
    ports:
      - "9483-9498:9483"
    deploy:
      replicas: 1
    environment:
      - OTEL_SERVICE_NAME=RatingService
    command:
      - /bin/sh
      - -c
      - |
        uvicorn rating_service:app --log-level critical  --host 0.0.0.0 --port 5004 &
        cd ../../
        while ! ~/go/bin/ebpf_exporter --config.file=go/ebpf_exporter/examples/runqlat.yaml --web.listen-address=":9483"
        do
          sleep 0.01
        done

  rating-mongodb:
    image: mongo
    container_name: rating-mongodb
    ports:
      - '27018:27017'
    command: mongod --quiet --logpath /dev/null


  movie-id-service:
    image: smj8612/media_reservation_mj:latest
    privileged: true # needed for ebpf_exporter
    volumes:
      - '/sys:/sys:ro'
      - '/usr/src:/usr/src:ro'
      - '/lib/modules:/lib/modules:ro'
    expose:
      - "5005" # needed for microservice
    ports:
      - "9499-9514:9499"
    deploy:
      replicas: 1
    environment:
      - OTEL_SERVICE_NAME=MovieIdService # The name of the service for OpenTelemetry
    command:
      - /bin/sh
      - -c
      - |
        uvicorn movie_id_service:app --log-level critical  --host 0.0.0.0 --port 5005 &
        cd ../../
        while ! ~/go/bin/ebpf_exporter --config.file=go/ebpf_exporter/examples/runqlat.yaml --web.listen-address=":9499"
        do
          sleep 0.01
        done
  

  movie-id-mongodb:
    image: mongo
    container_name: movie-id-mongodb
    ports:
      - '27019:27017'
    command: mongod --quiet --logpath /dev/null

  review-storage-service:
    image: smj8612/media_reservation_mj:latest
    privileged: true # needed for ebpf_exporter
    volumes:
      - '/sys:/sys:ro'
      - '/usr/src:/usr/src:ro'
      - '/lib/modules:/lib/modules:ro'
    expose:
      - "5006" # needed for microservice
    ports:
      - "9515-9530:9515"
    deploy:
      replicas: 1
    environment:
      - OTEL_SERVICE_NAME=ReviewStorageService # The name of the service for OpenTelemetry
    command:
      - /bin/sh
      - -c
      - |
        uvicorn review_storage_service:app --log-level critical  --host 0.0.0.0 --port 5006 &
        cd ../../
        while ! ~/go/bin/ebpf_exporter --config.file=go/ebpf_exporter/examples/runqlat.yaml --web.listen-address=":9515"
        do
          sleep 0.01
        done    

  review-storage-mongodb:
    image: mongo
    container_name: review-storage-mongodb
    ports:
      - '27020:27017'
    command: mongod --quiet --logpath /dev/null

  movie-review-service:
    image: smj8612/media_reservation_mj:latest
    privileged: true # needed for ebpf_exporter
    volumes:
      - '/sys:/sys:ro'
      - '/usr/src:/usr/src:ro'
      - '/lib/modules:/lib/modules:ro'
    expose:
      - "5007" # needed for microservice
    deploy:
      replicas: 1
    ports:
      - "9531-9546:9531"
    environment:
      - OTEL_SERVICE_NAME=MovieReview # The name of the service for OpenTelemetry
    command:
      - /bin/sh
      - -c
      - |
        uvicorn movie_review_service:app --log-level critical  --host 0.0.0.0 --port 5007 &
        cd ../../
        while ! ~/go/bin/ebpf_exporter --config.file=go/ebpf_exporter/examples/runqlat.yaml --web.listen-address=":9531"
        do
          sleep 0.01
        done
  

  movie-review-mongodb:
    image: mongo
    container_name: movie-review-mongodb
    ports:
      - '27021:27017'
    command: mongod --quiet --logpath /dev/null


  user-review-service:
    image: smj8612/media_reservation_mj:latest
    privileged: true # needed for ebpf_exporter
    volumes:
      - '/sys:/sys:ro'
      - '/usr/src:/usr/src:ro'
      - '/lib/modules:/lib/modules:ro'
    expose:
      - "5008" # needed for microservice
    ports:
      - "9547-9562:9547"
    deploy:
      replicas: 1
    depends_on:
      user-review-mongodb:
        condition: service_started
    environment:
      - OTEL_SERVICE_NAME=UserReviewService # The name of the service for OpenTelemetry
    command:
      - /bin/sh
      - -c
      - |
        uvicorn user_review_service:app --log-level critical  --host 0.0.0.0 --port 5008 &
        cd ../../
        while ! ~/go/bin/ebpf_exporter --config.file=go/ebpf_exporter/examples/runqlat.yaml --web.listen-address=":9547"
        do
          sleep 0.01
        done

  user-review-mongodb:
    image: mongo
    container_name: user-review-mongodb
    ports:
      - '27022:27017'
    command: mongod --quiet --logpath /dev/null

  compose-review-service:
    image: smj8612/media_reservation_mj:latest
    privileged: true # needed for ebpf_exporter
    volumes: # needed for ebpf_exporter
      - '/sys:/sys:ro'
      - '/usr/src:/usr/src:ro'
      - '/lib/modules:/lib/modules:ro'
    expose:
      - "5009" # nginx port
    ports:
      - "9563-9578:9563" # ebpf_exporter port
    deploy:
      replicas: 1
    environment:
      - OTEL_SERVICE_NAME=ComposeReviewService # The name of the service for OpenTelemetry
    command:
      - /bin/sh
      - -c
      - |
        uvicorn compose_review:app --log-level critical  --host 0.0.0.0 --port 5009 &
        cd ../../
        while ! ~/go/bin/ebpf_exporter --config.file=go/ebpf_exporter/examples/runqlat.yaml --web.listen-address=":9563"
        do
          sleep 0.01
        done
        

